// <auto-generated />
namespace MVCHCL.Day1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FkMembershipTypeIdtocustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FkMembershipTypeIdtocustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "201910030955296_FkMembershipTypeIdtocustomer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
